name:                blueprint
version:             0.1.0.0
github:              "Ei30metry/blueprint"
license:             BSD3
author:              "Artin Ghasivand"
maintainer:          "ghasivand.artin@gmail.com"
copyright:           "2022 Artin Ghasivand"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            A CLI Tool for seeing all the underlying blocks of functions and structures
category:            Development

description:         Please see the README on GitHub at <https://github.com/Ei30metry/blueprint#readme>

dependencies:
- base >= 4.7 && < 5
- text
- bytestring
- colour
- fmt
- containers
- transformers
- mtl
- hashable
- extra
- cereal
- optparse-applicative
- vector
- lens
- ghc-lib
- ghc-lib-parser
- ghc-source-gen
- ormolu
- haskell-src-exts

default-extensions:
  - MultiParamTypeClasses
  - GADTs
  - ScopedTypeVariables
  - OverloadedStrings
  - RankNTypes
  - TypeFamilies
  - TypeOperators
  - TypeApplications
  - DataKinds
  - PolyKinds
  - KindSignatures
  - StandaloneKindSignatures
  - RoleAnnotations

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -fforce-recomp

library:
  source-dirs: src


executables:
  blueprint-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blueprint

tests:
  blueprint-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blueprint
