name:                blueprint
version:             0.1.0.0
github:              "Ei30metry/blueprint"
license:             BSD3
author:              "Artin Ghasivand"
maintainer:          "ghasivand.artin@gmail.com"
copyright:           "2022 Artin Ghasivand"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            A CLI Tool for seeing all the underlying blocks of functions
category:            Development

description:         Please see the README on GitHub at <https://github.com/Ei30metry/blueprint#readme>

dependencies:
- base >= 4.7 && < 5
- text
- bytestring
- containers
- mtl
- transformers
- optparse-applicative
- lens
- ghc
- ghc-boot
# - ghc-lib
# - ghc-lib-parser
- ghc-paths
- cryptohash-sha1
- aeson
- aeson-pretty
- random
- open-browser
- diagrams-contrib
- diagrams-core
- diagrams-svg
- diagrams-lib
- hie-bios
- process
- directory
- filepath
- filepath
- unix
- unix-compat
- directory
- turtle
- foldl
- binary
- terminfo
- base16-bytestring
# - exceptions
# - ghc-prim
# - colour
# - fmt
# - extra
# - cereal
# - vector
# - monad-par
# - parallel
# - stack

default-extensions:
  - AllowAmbiguousTypes
  - PatternSynonyms
  - TupleSections
  - MultiParamTypeClasses
  - GADTs
  - ScopedTypeVariables
  - OverloadedStrings
  - RankNTypes
  - TypeFamilies
  - TypeOperators
  - TypeApplications
  - CPP
  - RecordWildCards
  - DataKinds
  - ViewPatterns
  - PolyKinds
  - DeriveGeneric
  - KindSignatures
  - StandaloneKindSignatures
  - StandaloneDeriving
  - RoleAnnotations
  - TemplateHaskell
  - EmptyCase
  - GeneralizedNewtypeDeriving
  - DeriveFunctor
  - LambdaCase
  - FlexibleContexts
  - DerivingStrategies
  - MagicHash

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
# - -fforce-recomp

library:
  source-dirs: src


executables:
  blueprint-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blueprint

tests:
  blueprint-test:
    main:                Tests.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blueprint
    - tasty
    - hedgehog
    - tasty-hedgehog
    - tasty-golden
